# Generated by Django 2.2.2 on 2019-06-28 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photodisplay', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
    ]
