# Generated by Django 2.2.2 on 2019-06-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photodisplay', '0002_auto_20190628_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='isauthor',
            field=models.BooleanField(default=False),
        ),
    ]
