# Generated by Django 2.2.2 on 2019-06-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photodisplay', '0003_auto_20190630_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='电子邮箱'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='', upload_to='photos/%Y/%m/%d/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='isauthor',
            field=models.BooleanField(default=False, verbose_name='是否作者'),
        ),
    ]
