# Generated by Django 2.2.2 on 2019-06-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photodisplay', '0004_auto_20190630_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='content',
            field=models.TextField(default='', verbose_name='自我介绍'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='content',
            field=models.TextField(verbose_name='正文'),
        ),
    ]
