# Generated by Django 2.2.2 on 2019-07-02 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photodisplay', '0005_auto_20190630_2042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['created_time'], 'verbose_name': '照片', 'verbose_name_plural': '照片'},
        ),
    ]
