# Generated by Django 2.2.2 on 2019-07-02 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photodisplay', '0006_auto_20190702_0847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['-created_time'], 'verbose_name': '照片', 'verbose_name_plural': '照片'},
        ),
    ]
