# Generated by Django 2.2.2 on 2019-07-27 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photodisplay', '0008_honor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Honor',
        ),
    ]
