# Generated by Django 2.2.2 on 2019-07-28 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photodisplay', '0011_homephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homephoto',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='photodisplay.UserProfile', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='honor',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='photodisplay.UserProfile', verbose_name='用户'),
        ),
    ]
